---
extends: airbnb-base
parserOptions:
  ecmaVersion: 2020
env:
  node: true
  mocha: true
  es6: true
plugins:
  - chai-friendly
rules:
  arrow-parens:
    - error
    - always
  # array-bracket-spacing:
  #   - error
  #   - always
  #   - objectsInArrays: false
  #     arraysInArrays: false
  #     singleValue: true
  eqeqeq: 0
  chai-friendly/no-unused-expressions: 2
  comma-dangle: 0
  consistent-return: 0
  function-paren-newline:
    - error
    - consistent
  implicit-arrow-linebreak:
    - 'off'
  import/extensions:
    - error
    - always
    - ignorePackages: true
  import/prefer-default-export: 0
  indent:
    - error
    - 2
  max-len: 0
  no-console: 0
  no-param-reassign: 0
  no-plusplus: 0
  no-restricted-syntax: 0
  no-shadow: 0
  no-tabs: 0
  no-underscore-dangle: 0
  no-unused-expressions: 0
  no-unused-vars:
    - error
    - argsIgnorePattern: next
  no-use-before-define: 0
  object-curly-newline: 0
