extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 2022
env:
  node: true
  mocha: true
  es6: true
plugins:
  - chai-friendly
  - import
  - json-format
rules:
  arrow-parens:
    - error
    - as-needed
  array-bracket-spacing:
    - error
    - always
    - objectsInArrays: false
      arraysInArrays: false
      singleValue: false
  eqeqeq: 0
  chai-friendly/no-unused-expressions: 2
  comma-dangle:
    - error
    - always-multiline
  consistent-return: 0
  function-paren-newline:
    - error
    - multiline
  implicit-arrow-linebreak:
    - 'off'
  import/extensions:
    - error
    - always
    - ignorePackages: true
  import/prefer-default-export: 0
  import/order:
    - error
    - newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
  import/namespace:
    - error
    - allowComputed: true
  indent:
    - error
    - 2
  max-len: 0
  object-curly-newline:
    - error
    - multiline: true
  no-console: 0
  no-continue: 0
  no-param-reassign: 0
  no-plusplus: 0
  no-restricted-syntax: 0
  no-shadow: 0
  no-tabs: 0
  no-underscore-dangle: 0
  no-unused-expressions: 0
  no-unused-vars:
    - error
    - argsIgnorePattern: next
  no-use-before-define: 0
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: '*'
      next: return
    - blankLine: always
      prev:
        - const
        - let
        - var
      next: '*'
    - blankLine: any
      prev:
        - const
        - let
        - var
      next:
        - const
        - let
        - var
  multiline-comment-style:
    - error
    - separate-lines
  eol-last:
    - error
    - always
  new-cap:
    - error
    - properties: false

overrides:
  - files:
      - src/**/*test.js
      - scripts/declarations/validate/*.js
    rules:
      func-names: 0
  - files:
      - scripts/**/*.js
      - bin/**/*.js
    rules:
      func-names: 0
      import/no-extraneous-dependencies: 0
  - files:
      - src/**/*[iI]nterface.js
    rules:
      no-unused-vars: 0
      require-yield: 0
      class-methods-use-this: 0
      no-empty-function: 0
