all:
  vars:
    snapshots_branch: main
    versions_branch: main
    snapshots_directory: snapshots
    versions_directory: version
    declarations_directory: declarations
  children:
    dev:
      hosts:
        '127.0.0.1':
          ansible_ssh_port: 2222
          ansible_user: vagrant
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/ota-vagrant
          services_repository: https://github.com/OpenTermsArchive/contrib-declarations.git
          snapshots_repository: git@github.com:OpenTermsArchive/contrib-snapshots.git
          snapshots_branch: master
          versions_repository: git@github.com:OpenTermsArchive/contrib-versions.git
          versions_branch: master

