all:
  children:
    dev:
      hosts:
        '127.0.0.1':
          ansible_ssh_port: 2222
          ansible_user: vagrant
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_private_key_file: ~/.ssh/ota-vagrant
          services_directory: ota-contrib-declarations
          services_repository: https://github.com/OpenTermsArchive/contrib-declarations.git
          snapshots_directory: ota-snapshots
          snapshots_repository: git@github.com:ambanum/OpenTermsArchive-snapshots.git
          snapshots_branch: master
          versions_directory: ota-versions
          versions_repository: git@github.com:ambanum/OpenTermsArchive-versions.git
          versions_branch: master

