all:
  children:
    dev:
      hosts:
        '127.0.0.1':
          ansible_ssh_port: 2223
          ansible_user: vagrant
          ansible_ssh_private_key_file: ../disinfo.quaidorsay.fr-ops/.vagrant/machines/ota/virtualbox/private_key
          ansible_ssh_extra_args: -o StrictHostKeyChecking=no -o IdentitiesOnly=yes
