all:
  vars:
    ansible_user: debian
    snapshots_branch: main
    versions_branch: main
    snapshots_directory: snapshots
    versions_directory: version
    declarations_directory: declarations
  children:
    production:
      children:
        services_all:
          hosts:
            51.89.227.206:
              services_repository: https://github.com/OpenTermsArchive/contrib-declarations.git
              snapshots_repository: git@github.com:OpenTermsArchive/contrib-snapshots.git
              snapshots_branch: master
              versions_repository: git@github.com:OpenTermsArchive/contrib-versions.git
              versions_branch: master
        dating:
          hosts:
            vps-99ae1d89.vps.ovh.net:
              services_repository: https://github.com/OpenTermsArchive/dating-declarations.git
              snapshots_repository: git@github.com:OpenTermsArchive/dating-snapshots.git
              versions_repository: git@github.com:OpenTermsArchive/dating-versions.git
        france:
          hosts:
            198.244.142.9:
              services_repository: https://github.com/OpenTermsArchive/france-declarations.git
              snapshots_repository: git@github.com:OpenTermsArchive/france-snapshots.git
              versions_repository: git@github.com:OpenTermsArchive/france-versions.git
        france_elections:
          hosts:
            198.244.140.194:
              services_repository: https://github.com/OpenTermsArchive/france-elections-declarations.git
              snapshots_repository: git@github.com:OpenTermsArchive/france-elections-snapshots.git
              versions_repository: git@github.com:OpenTermsArchive/france-elections-versions.git
