all:
  vars:
    ansible_user: debian
    snapshots_branch: main
    versions_branch: main
    snapshots_directory: snapshots
    versions_directory: versions
    declarations_directory: declarations
    app_directory: ota
    ota_repository: https://github.com/ambanum/OpenTermsArchive.git
    ota_branch: main
    app_config: "{{ lookup('file','../config/{{config_file_name}}.json') | from_json }}"
  children:
    production:
      children:
        contrib:
          hosts:
            51.89.227.206:
              config_file_name: contrib
        dating:
          hosts:
            vps-99ae1d89.vps.ovh.net:
              config_file_name: dating
        france:
          hosts:
            198.244.142.9:
              config_file_name: france
        france_elections:
          hosts:
            198.244.140.194:
              config_file_name: france-elections
        pga:
          hosts:
            134.102.58.70:
              ansible_user: pga
              config_file_name: pga
        p2b_compliance:
          hosts:
            vps-463f0baf.vps.ovh.net:
              ansible_user: ota
              config_file_name: p2b-compliance
