all:
  vars:
    ansible_user: debian
    snapshots_branch: main
    versions_branch: main
    snapshots_directory: snapshots
    versions_directory: versions
    declarations_directory: declarations
    app_directory: ota
    ota_repository: https://github.com/ambanum/OpenTermsArchive.git
    ota_branch: main
  children:
    production:
      children:
        contrib:
          hosts:
            51.89.227.206:
              config_file_name: contrib
              services_repository: https://github.com/OpenTermsArchive/contrib-declarations.git
              snapshots_repository: git@github.com:OpenTermsArchive/contrib-snapshots.git
              snapshots_branch: master
              versions_repository: git@github.com:OpenTermsArchive/contrib-versions.git
              versions_branch: main
        dating:
          hosts:
            vps-99ae1d89.vps.ovh.net:
              config_file_name: dating
              services_repository: https://github.com/OpenTermsArchive/dating-declarations.git
              snapshots_repository: git@github.com:OpenTermsArchive/dating-snapshots.git
              versions_repository: git@github.com:OpenTermsArchive/dating-versions.git
        france:
          hosts:
            198.244.142.9:
              config_file_name: france
              services_repository: https://github.com/OpenTermsArchive/france-declarations.git
              snapshots_repository: git@github.com:OpenTermsArchive/france-snapshots.git
              versions_repository: git@github.com:OpenTermsArchive/france-versions.git
        france_elections:
          hosts:
            198.244.140.194:
              config_file_name: france-elections
              services_repository: https://github.com/OpenTermsArchive/france-elections-declarations.git
              snapshots_repository: git@github.com:OpenTermsArchive/france-elections-snapshots.git
              versions_repository: git@github.com:OpenTermsArchive/france-elections-versions.git
