---
# See https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/
- name: Import the MongoDB public key used by the package management system
  shell: wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -

- name: Create an apt list file for MongoDB — Debian
  shell: echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
  when: ansible_distribution == 'Debian'

- name: Create an apt list file for MongoDB — Ubuntu
  shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
  when: ansible_distribution == 'Ubuntu'

- name: Install MongoDB
  apt:
    name: mongodb-org
    update_cache: yes
    state: latest

- name: Add mongod.conf
  copy:
    src: mongod.conf
    dest: '/etc/mongod.conf'

- name: Create data directory
  file:
    path: /mnt/disk/mongodb
    state: directory

- name: Set database files permissions
  ansible.builtin.file:
    path: /mnt/disk/mongodb
    owner: mongodb
    group: mongodb
    recurse: yes

- name: Start MongoDB service
  service:
    name: mongod
    state: restarted
