- name: Check if {{ name }} base data has already been obtained from {{ repository }}
  git:
    repo: '{{ repository }}'
    version: '{{ branch }}'
    dest: '/home/{{ ansible_user }}/{{ directory }}'
    clone: no
    update: no
    accept_hostkey: yes
    key_file: '/home/{{ ansible_user }}/.ssh/ota-bot-key'
  register: existing_repository # the `before` property of the return value can tell us if the repository has been cloned already or not, see <https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html#return-values>
  tags:
    - restart
    - start
    - update
    - setup

- name: Obtain {{ name }} initial data from branch {{ branch }} of {{ repository }}
  git:
    repo: '{{ repository }}'
    version: '{{ branch }}'
    dest: '/home/{{ ansible_user }}/{{ directory }}'
    accept_hostkey: yes
    key_file: '/home/{{ ansible_user }}/.ssh/ota-bot-key'
  when: existing_repository.before is defined and not existing_repository.before # if existing_repository.before is null, then the repository is new
  tags:
    - setup

- name: Remove existing locks in {{ name }}
  file:
    path: '/home/{{ ansible_user }}/{{ directory }}/.git/index.lock'
    state: absent
  tags:
    - restart
    - start
    - update

- name: Get latest data from {{ repository }}
  command:
    cmd: git fetch origin
    chdir: '/home/{{ ansible_user }}/{{ directory }}'
  tags:
    - restart
    - start
    - update
    - setup

- name: Clean {{ name }} local copy
  command:
    cmd: git reset --hard origin/{{ branch }}
    chdir: '/home/{{ ansible_user }}/{{ directory }}'
  tags:
    - restart
    - start
    - update
    - setup

- name: Ensure {{ name }} is on branch {{ branch }}
  command:
    cmd: git checkout {{ branch }}
    chdir: '/home/{{ ansible_user }}/{{ directory }}'
  tags:
    - restart
    - start
    - update
    - setup
