---
- name: Set up Open Terms Archive infrastructure and engine
  hosts: all
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Load app config
      include_vars:
        name: app_config
        file: '../config/production.json'

    - name: Set up infrastructure
      include_role:
        name: infrastructure
        apply:
          become: yes
          tags: infra

    - name: Set up engine
      include_role:
        name: engine
