name: Deploy

on:
  push:
    branches: [ fix-deploy-reusable-workflow ]

jobs:
  test:
    uses: "ambanum/OpenTermsArchive/.github/workflows/test.yml@main"

  get_instances:
    uses: "ambanum/OpenTermsArchive/.github/workflows/get_instances.yml@main"

  deploy:
    needs:
      - get_instances
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # deploy other instances even if one fails to deploy
      matrix:
        instance: ${{ fromJSON(needs.get_instances.outputs.names) }}
    steps:
      - uses: actions/checkout@v2
      - name: Obtain known host entry
        id: get_known_host_entry
        uses: ./get_instances.yml
        with:
          instance: ${{ matrix.instance }}
      - name: Set up SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ steps.get_known_host_entry.outputs.known_host_entry }}
      - run: echo "${{ secrets.ANSIBLE_VAULT_KEY }}" > vault.key
      - run: pip install --upgrade setuptools
      - run: pip install 'ansible ~= 2.9'
      - run: ansible-playbook ops/site.yml --inventory ops/inventories/production.yml --limit ${{ matrix.instance }}
